#Planned joint trajectory
array2d_double joint_trajectory

#Planned endeffector trajectory
array2d_double ee_trajectory

---

#Flag indicating whether trajectory execution has been successfull
bool execution_success